export const FETCH_DASHBOARD_DATA = 'FETCH_DASHBOARD_DATA';
export const FETCH_STUDENT_DETAILS = 'FETCH_STUDENT_DETAILS';
export const SORT_BY_NAME = 'SORT_BY_NAME';
export const SORT_BY_MARKS = 'SORT_BY_MARKS';
export const SEARCH_STUDENTS_BY_NAME = 'SEARCH_STUDENTS_BY_NAME';